version: 2
jobs:
  build-web-job:
    working_directory: /tmp/about
    docker:
      - image: node:9

    steps:
      - checkout

      - run:
          name: Create workspace directory
          command: |
            mkdir -p /tmp/workspace/www

      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-

      - run:
          name: Install node packages
          command: |
            yarn add gulp@next
            yarn install --production=false --check-files --pure-lockfile --network-concurrency=32 --non-interactive

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ epoch }}

      - run:
          name: Install dependencies
          command: |
            node_modules/.bin/gulp less

      - persist_to_workspace:
          root: /tmp/workspace/
          paths:
            - www

  deploy-job:
    docker:
      - image: circleci/python:3.6.2
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - restore_cache:
          name: Restore Python virtual environment cache
          keys:
          - v1-venv-deploy-{{ .Branch }}-
          - v1-venv-deploy-

      - run:
          name: Create virtualenv
          command: |
            python3 -m venv /tmp/venv

      - run:
          name: Install Python dependencies
          command: |
            source /tmp/venv/bin/activate
            pip install --no-input --compile --exists-action=a --use-wheel --upgrade awscli

      - save_cache:
          paths:
            - /tmp/venv/
          key: v1-venv-deploy-{{ .Branch }}-{{ epoch }}

      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            source /tmp/venv/bin/activate

            aws s3 sync /tmp/workspace/www s3://${S3_BUCKET_NAME}/ --delete
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-web-job
      - deploy-job:
          requires:
            - build-web-job
          filters:
            branches:
              only: master
